spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp_high?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

#日志配置
#trace是日志最低级别，可以输出更多的细节
logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'